// Every word the dashboard shows, in every language it speaks.
//
// The table is keyed by the English string the code already writes, so a screen reads the same
// either way and a missing translation falls back to English rather than to a key nobody can read.
// A key can carry a context after a bar, "All|sites", because a Spanish adjective agrees with the
// noun it describes and one English word can need two Spanish ones. The fallback is the text before
// the bar, so a missing entry still reads.
//
// Spanish is written as \u escapes: every file under src/ is plain ASCII, and the accented text as
// the screen draws it lives in translation/dashboard_words.csv, which is what a translator reads
// and edits. The audit fails the run if the two ever disagree.
//
// A third language is one more key in each entry and one more id in LOCALES.
"use strict";

export const LOCALES = ["en", "es"];

// What a formatter is given. es-US rather than plain es: the company writes 1,234,567.50, and plain
// es writes 1.234.567,50.
export const LOCALE_TAGS = { en: "en-US", es: "es-US" };

// Each name is written in its own language and is never translated.
export const LANGUAGES = [
  { id: "en", label: "English" },
  { id: "es", label: "Espa\u00f1ol" },
];

export const WORDS = {
  "2150000000 or name@email.com": { es: "2150000000 o nombre@correo.com" },
  "< Prev": { es: "< Anterior" },
  "A staff member is requesting to drop this shift.": { es: "Una persona solicita darse de baja de este turno." },
  "A staff member is requesting to drop this shift. Approve to open it for pickup, deny to keep the original assignment, or reassign directly.": { es: "Una persona solicita darse de baja de este turno. Apruebe para abrirlo a quien quiera tomarlo, deniegue para dejar la asignaci\u00f3n original, o reasigne directamente." },
  "A staff member is requesting to drop this shift. Approve to open it for pickup, or deny to keep it assigned.": { es: "Una persona solicita darse de baja de este turno. Apruebe para abrirlo a quien quiera tomarlo, o deniegue para dejarlo asignado." },
  "Actions": { es: "Acciones" },
  "Active": { es: "Activo" },
  "Additional details about this shift...": { es: "Detalles adicionales sobre este turno..." },
  "Admin": { es: "Administrador" },
  "Admin Dashboard": { es: "Panel de administraci\u00f3n" },
  "Admin access required": { es: "Se requiere acceso de administrador" },
  "Administrator": { es: "Administrador" },
  "All Reasons": { es: "Todos los motivos" },
  "All Sites": { es: "Todos los sitios" },
  "All people": { es: "Todas las personas" },
  "All sites": { es: "Todos los sitios" },
  "Analytics": { es: "An\u00e1lisis" },
  "Approve": { es: "Aprobar" },
  "Approve Drop": { es: "Aprobar la baja" },
  "Approved": { es: "Aprobada" },
  "Approved Shift": { es: "Turno aprobado" },
  "Asked": { es: "Solicitado" },
  "Assign": { es: "Asignar" },
  "Assigned": { es: "Asignado" },
  "Assigned Supervisor": { es: "Supervisor asignado" },
  "Assigned Tasks": { es: "Tareas asignadas" },
  "Average": { es: "Promedio" },
  "Avg (min)": { es: "Prom. (min)" },
  "Avg Fill Time": { es: "Tiempo medio de cobertura" },
  "Back to Dashboard": { es: "Volver al panel" },
  "Bldg: {0}": { es: "Edificio: {0}" },
  "Building": { es: "Edificio" },
  "CLAIMED": { es: "TOMADO" },
  "Callout": { es: "Ausencia" },
  "Callout Patterns": { es: "Patrones de ausencias" },
  "Callouts": { es: "Ausencias" },
  "Cancel": { es: "Cancelar" },
  "Cancel Inspection": { es: "Cancelar la inspecci\u00f3n" },
  "Cancel ending this pattern": { es: "Cancelar el fin de este patr\u00f3n" },
  "Cancel this date": { es: "Cancelar esta fecha" },
  "Cancelled": { es: "Cancelado" },
  "Cancelled by the person who asked": { es: "Cancelada por quien la solicit\u00f3" },
  "Cases": { es: "Casos" },
  "Change": { es: "Cambiar" },
  "Changes start on": { es: "Los cambios comienzan el" },
  "Claimed": { es: "Tomado" },
  "Claimed By": { es: "Tomado por" },
  "Claimed Pickup Shift": { es: "Turno disponible tomado" },
  "Claims": { es: "Turnos tomados" },
  "Close": { es: "Cerrar" },
  "Collapse sidebar": { es: "Contraer el panel lateral" },
  "Completed": { es: "Completado" },
  "Confirm Convert": { es: "Confirmar la conversi\u00f3n" },
  "Confirm ending this pattern": { es: "Confirmar el fin de este patr\u00f3n" },
  "Connected to Live API": { es: "Conectado a la API en vivo" },
  "Convert": { es: "Convertir" },
  "Convert Callout": { es: "Convertir la ausencia" },
  "Convert Scheduled Shift to Open Pickup": { es: "Convertir un turno programado en turno abierto" },
  "Convert to Open Pickup": { es: "Convertir en turno abierto" },
  "Coverage by Site": { es: "Cobertura por sitio" },
  "Custom": { es: "Personalizado" },
  "DROP REQ": { es: "SOL. DE BAJA" },
  "Dark Mode": { es: "Modo oscuro" },
  "Dark mode": { es: "Modo oscuro" },
  "Dashboard": { es: "Panel" },
  "Date": { es: "Fecha" },
  "Date *": { es: "Fecha *" },
  "Date is required": { es: "La fecha es obligatoria" },
  "Dates": { es: "Fechas" },
  "Days": { es: "D\u00edas" },
  "Decided": { es: "Decidido" },
  "Decided by": { es: "Decidido por" },
  "Delete": { es: "Eliminar" },
  "Denied": { es: "Denegada" },
  "Deny": { es: "Denegar" },
  "Deny Request": { es: "Denegar la solicitud" },
  "Done": { es: "Listo" },
  "Drop Req": { es: "Sol. de baja" },
  "Drop Request": { es: "Solicitud de baja" },
  "Drop Requested": { es: "Baja solicitada" },
  "Drop Requests": { es: "Solicitudes de baja" },
  "Drop approved": { es: "Baja aprobada" },
  "Drop approved, shift is now open": { es: "Baja aprobada, el turno queda abierto" },
  "Drop approved, shift is open": { es: "Baja aprobada, el turno queda abierto" },
  "Drop request denied": { es: "Solicitud de baja denegada" },
  "Edit": { es: "Editar" },
  "Edit Scheduled Shift": { es: "Editar el turno programado" },
  "End": { es: "Fin" },
  "End Time": { es: "Hora de fin" },
  "End Time *": { es: "Hora de fin *" },
  "End pattern": { es: "Terminar el patr\u00f3n" },
  "End this pattern after": { es: "Terminar este patr\u00f3n despu\u00e9s del" },
  "End this pattern after {0}? Future shifts it added are removed, except ones changed by hand.": { es: "\u00bfTerminar este patr\u00f3n despu\u00e9s del {0}? Los turnos futuros que agreg\u00f3 se eliminan, salvo los que se cambiaron a mano." },
  "End time": { es: "Hora de fin" },
  "Ended": { es: "Terminado" },
  "Ends": { es: "Termina" },
  "Enter": { es: "Ingrese" },
  "Everyone": { es: "Todos" },
  "Expand sidebar": { es: "Ampliar el panel lateral" },
  "Extra Coverage": { es: "Cobertura adicional" },
  "Extra large": { es: "Muy grande" },
  "Fastest": { es: "M\u00e1s r\u00e1pido" },
  "Fill Rate": { es: "Tasa de cobertura" },
  "Fill Rate by Reason": { es: "Tasa de cobertura por motivo" },
  "Filled through {0}": { es: "Cubierto hasta el {0}" },
  "Floor": { es: "Piso" },
  "Floor {0}": { es: "Piso {0}" },
  "Floor: {0}": { es: "Piso: {0}" },
  "Forms": { es: "Formularios" },
  "Fri": { es: "Vie" },
  "HR Records": { es: "Expedientes de personal" },
  "Help": { es: "Ayuda" },
  "Hours": { es: "Horas" },
  "Inspection": { es: "Inspecci\u00f3n" },
  "Inspection Details": { es: "Detalles de la inspecci\u00f3n" },
  "Inspection cancelled": { es: "Inspecci\u00f3n cancelada" },
  "Inspection rescheduled": { es: "Inspecci\u00f3n reprogramada" },
  "Inspection scores by site": { es: "Puntajes de inspecci\u00f3n por sitio" },
  "Inspections": { es: "Inspecciones" },
  "Integrations": { es: "Integraciones" },
  "Inventory": { es: "Inventario" },
  "Issue Tracker": { es: "Registro de incidencias" },
  "Issues": { es: "Incidencias" },
  "LIVE": { es: "EN VIVO" },
  "Language": { es: "Idioma" },
  "Large": { es: "Grande" },
  "Largest": { es: "M\u00e1ximo" },
  "Last 30 Days": { es: "\u00daltimos 30 d\u00edas" },
  "Last 90 Days": { es: "\u00daltimos 90 d\u00edas" },
  "Last Week": { es: "La semana pasada" },
  "Last day": { es: "\u00daltimo d\u00eda" },
  "Light Mode": { es: "Modo claro" },
  "Light mode": { es: "Modo claro" },
  "Live Operations": { es: "Operaciones en vivo" },
  "Live Ops": { es: "Operaciones en vivo" },
  "Load more": { es: "Ver m\u00e1s" },
  "Loading buildings...": { es: "Cargando los edificios..." },
  "Loading patterns...": { es: "Cargando los patrones..." },
  "Loading schedule...": { es: "Cargando el horario..." },
  "Loading time off...": { es: "Cargando el tiempo libre..." },
  "Loading...": { es: "Cargando..." },
  "Logout": { es: "Cerrar sesi\u00f3n" },
  "Mark all read": { es: "Marcar todo como le\u00eddo" },
  "Median": { es: "Mediana" },
  "Median (min)": { es: "Mediana (min)" },
  "Messages": { es: "Mensajes" },
  "Mon": { es: "Lun" },
  "Month": { es: "Mes" },
  "Monthly Totals": { es: "Totales del mes" },
  "Most recent inspection per site": { es: "Inspecci\u00f3n m\u00e1s reciente por sitio" },
  "New Shift": { es: "Turno nuevo" },
  "New Shifts": { es: "Turnos nuevos" },
  "Next": { es: "Siguiente" },
  "Next >": { es: "Siguiente >" },
  "Next Week": { es: "La pr\u00f3xima semana" },
  "No Show": { es: "No se present\u00f3" },
  "No buildings configured": { es: "No hay edificios configurados" },
  "No end": { es: "Sin fin" },
  "No end date": { es: "Sin fecha de fin" },
  "No inspections recorded yet.": { es: "Todav\u00eda no hay inspecciones registradas." },
  "No matching pages": { es: "Ninguna p\u00e1gina coincide" },
  "No note": { es: "Sin nota" },
  "No patterns yet. Turn on Repeat when adding a shift to create one.": { es: "Todav\u00eda no hay patrones. Active Repetir al agregar un turno para crear uno." },
  "No pickup activity found in this period.": { es: "No hay actividad de turnos disponibles en este periodo." },
  "No reason given": { es: "Sin motivo" },
  "No shifts found for this period and filter.": { es: "No hay turnos en este periodo con este filtro." },
  "No shifts on these days.": { es: "No hay turnos en estos d\u00edas." },
  "No shifts started yet today.": { es: "Todav\u00eda no ha iniciado ning\u00fan turno hoy." },
  "No specific service": { es: "Ning\u00fan servicio en particular" },
  "No staff match that search": { es: "Ninguna persona coincide con esa b\u00fasqueda" },
  "No upcoming scheduled shifts found.": { es: "No hay turnos programados pr\u00f3ximos." },
  "No-Show": { es: "No se present\u00f3" },
  "No-Shows": { es: "No se presentaron" },
  "Normal": { es: "Normal" },
  "Note": { es: "Nota" },
  "Notes": { es: "Notas" },
  "Nothing changed yet.": { es: "Nada ha cambiado todav\u00eda." },
  "Nothing yet.": { es: "Nada todav\u00eda." },
  "Notifications": { es: "Avisos" },
  "Notifications did not load.": { es: "Los avisos no se cargaron." },
  "OPEN": { es: "ABIERTO" },
  "OT Risk": { es: "Riesgo de horas extra" },
  "Open": { es: "Abierto" },
  "Open Issues": { es: "Incidencias abiertas" },
  "Open Marketplace Shift": { es: "Turno abierto en el tablero" },
  "Open Now": { es: "Abiertos ahora" },
  "Open shift posted": { es: "Turno abierto publicado" },
  "Open that pattern": { es: "Abrir ese patr\u00f3n" },
  "Open the pattern": { es: "Abrir el patr\u00f3n" },
  "Operations": { es: "Operaciones" },
  "Operations overview.": { es: "Resumen de operaciones." },
  "Optional notes": { es: "Notas opcionales" },
  "Optional when approving. Required when denying.": { es: "Opcional al aprobar. Obligatoria al denegar." },
  "Originally Assigned": { es: "Asignado originalmente" },
  "Overtime risk: claiming this shift may push the worker past 40 weekly hours.": { es: "Riesgo de horas extra: tomar este turno puede llevar a la persona a m\u00e1s de 40 horas semanales." },
  "Overview": { es: "Resumen" },
  "PIN": { es: "PIN" },
  "Page {0}": { es: "P\u00e1gina {0}" },
  "Page {0} / {1}": { es: "P\u00e1gina {0} / {1}" },
  "Part of a weekly pattern. Changes here apply to this date only.": { es: "Parte de un patr\u00f3n semanal. Los cambios aqu\u00ed se aplican solo a esta fecha." },
  "Patterns": { es: "Patrones" },
  "Pending": { es: "Pendiente" },
  "Person": { es: "Persona" },
  "Phone or Email": { es: "Tel\u00e9fono o correo" },
  "Pickup": { es: "Turno disponible" },
  "Pickup Shift": { es: "Turno disponible" },
  "Post Open Shift": { es: "Publicar turno abierto" },
  "Post Shift": { es: "Publicar turno" },
  "Prev": { es: "Anterior" },
  "Quality": { es: "Calidad" },
  "Reason": { es: "Motivo" },
  "Reason Breakdown": { es: "Desglose por motivo" },
  "Reassign To": { es: "Reasignar a" },
  "Recorded when the person started the shift in the portal. There is no end time and no hours here.": { es: "Registrado cuando la persona inici\u00f3 el turno en el portal. Aqu\u00ed no hay hora de fin ni horas." },
  "Refresh": { es: "Actualizar" },
  "Release": { es: "Liberar" },
  "Released": { es: "Liberado" },
  "Reliability": { es: "Cumplimiento" },
  "Repeat on": { es: "Repetir los" },
  "Repeat this shift": { es: "Repetir este turno" },
  "Repeats": { es: "Se repite" },
  "Replaces an earlier pattern": { es: "Reemplaza a un patr\u00f3n anterior" },
  "Reports": { es: "Informes" },
  "Request denied": { es: "Solicitud denegada" },
  "Request failed": { es: "La solicitud fall\u00f3" },
  "Requested": { es: "Solicitado" },
  "Requested By": { es: "Solicitado por" },
  "Requests": { es: "Solicitudes" },
  "Reschedule": { es: "Reprogramar" },
  "Response Time": { es: "Tiempo de respuesta" },
  "Response Time Summary": { es: "Resumen del tiempo de respuesta" },
  "Response Time by Site": { es: "Tiempo de respuesta por sitio" },
  "Response Time by Urgency": { es: "Tiempo de respuesta por urgencia" },
  "Sat": { es: "S\u00e1b" },
  "Save": { es: "Guardar" },
  "Save Changes": { es: "Guardar los cambios" },
  "Save changes": { es: "Guardar los cambios" },
  "Schedule": { es: "Horario" },
  "Schedule All": { es: "Programar todo" },
  "Schedule Shift": { es: "Programar turno" },
  "Schedule updated": { es: "Horario actualizado" },
  "Scheduled": { es: "Programado" },
  "Scheduled Date *": { es: "Fecha programada *" },
  "Scheduling for": { es: "Programando para" },
  "Score": { es: "Puntaje" },
  "Search pages": { es: "Buscar p\u00e1ginas" },
  "Search site, service, staff, notes": { es: "Buscar por sitio, servicio, personal o notas" },
  "Search staff": { es: "Buscar personal" },
  "Search staff...": { es: "Buscar personal..." },
  "Select a scheduled shift below. The original shift will be cancelled and replaced with an open pickup that eligible staff can claim.": { es: "Seleccione un turno programado abajo. El turno original se cancela y se reemplaza por un turno abierto que el personal elegible puede tomar." },
  "Select a staff member": { es: "Seleccione a una persona" },
  "Select building...": { es: "Seleccione un edificio..." },
  "Select floor...": { es: "Seleccione un piso..." },
  "Select site...": { es: "Seleccione un sitio..." },
  "Select staff member...": { es: "Seleccione a la persona..." },
  "Select staff...": { es: "Seleccione personal..." },
  "Select...": { es: "Seleccione..." },
  "Service": { es: "Servicio" },
  "Service Catalog": { es: "Cat\u00e1logo de servicios" },
  "Service Category": { es: "Categor\u00eda de servicio" },
  "Service category": { es: "Categor\u00eda de servicio" },
  "Services": { es: "Servicios" },
  "Settings": { es: "Configuraci\u00f3n" },
  "Shift": { es: "Turno" },
  "Shift Details": { es: "Detalles del turno" },
  "Shift Drop Request": { es: "Solicitud de baja de turno" },
  "Shift Pickup": { es: "Turnos disponibles" },
  "Shift Pickup Board": { es: "Tablero de turnos disponibles" },
  "Shift approved": { es: "Turno aprobado" },
  "Shift assigned": { es: "Turno asignado" },
  "Shift cancelled": { es: "Turno cancelado" },
  "Shift converted to open pickup": { es: "Turno convertido en turno abierto" },
  "Shift reassigned": { es: "Turno reasignado" },
  "Shift released": { es: "Turno liberado" },
  "Shift removed": { es: "Turno eliminado" },
  "Shift scheduled": { es: "Turno programado" },
  "Shift updated": { es: "Turno actualizado" },
  "Shifts": { es: "Turnos" },
  "Shifts before this date stay as they are. Shifts someone changed or cancelled by hand are kept.": { es: "Los turnos anteriores a esta fecha quedan como est\u00e1n. Los turnos que alguien cambi\u00f3 o cancel\u00f3 a mano se conservan." },
  "Shifts by Day of Week": { es: "Turnos por d\u00eda de la semana" },
  "Shifts on these days": { es: "Turnos en estos d\u00edas" },
  "Showing {0} to {1} of {2}": { es: "Mostrando {0} a {1} de {2}" },
  "Sign In": { es: "Iniciar sesi\u00f3n" },
  "Sign Out": { es: "Cerrar sesi\u00f3n" },
  "Signing in...": { es: "Iniciando sesi\u00f3n..." },
  "Since midnight": { es: "Desde la medianoche" },
  "Site": { es: "Sitio" },
  "Site *": { es: "Sitio *" },
  "Site x Day Heatmap": { es: "Mapa de calor de sitio por d\u00eda" },
  "Site, date, and times are required": { es: "El sitio, la fecha y las horas son obligatorios" },
  "Sites": { es: "Sitios" },
  "Slowest": { es: "M\u00e1s lento" },
  "Staff": { es: "Personal" },
  "Staff Management": { es: "Gesti\u00f3n de personal" },
  "Staff Member": { es: "Persona" },
  "Staff Member *": { es: "Persona *" },
  "Staff Reliability": { es: "Cumplimiento del personal" },
  "Staff Reliability Metrics": { es: "Indicadores de cumplimiento del personal" },
  "Staff at this site...": { es: "Personal de este sitio..." },
  "Staff, site, start time, and end time are required": { es: "La persona, el sitio, la hora de inicio y la hora de fin son obligatorios" },
  "Standard": { es: "Est\u00e1ndar" },
  "Start": { es: "Inicio" },
  "Start Time": { es: "Hora de inicio" },
  "Start Time *": { es: "Hora de inicio *" },
  "Start time": { es: "Hora de inicio" },
  "Started": { es: "Iniciado" },
  "Started Shift": { es: "Turno iniciado" },
  "Started today": { es: "Iniciados hoy" },
  "Starts": { es: "Comienza" },
  "Status": { es: "Estado" },
  "Sun": { es: "Dom" },
  "Supervisor": { es: "Supervisor" },
  "Supplies": { es: "Suministros" },
  "Supplies & Inventory": { es: "Suministros e inventario" },
  "Task progress": { es: "Avance de tareas" },
  "Text size": { es: "Tama\u00f1o del texto" },
  "That one is for admins. Ask an admin to take a look.": { es: "Ese es para administradores. P\u00eddale a un administrador que lo revise." },
  "The schedule fills 8 weeks ahead and keeps extending until the pattern is ended.": { es: "El horario se llena con 8 semanas de anticipaci\u00f3n y sigue extendi\u00e9ndose hasta que el patr\u00f3n termine." },
  "The scheduled shift will be cancelled and posted as an open shift for eligible staff to claim.": { es: "El turno programado se cancela y se publica como turno abierto para que el personal elegible lo tome." },
  "This Month": { es: "Este mes" },
  "This Week": { es: "Esta semana" },
  "This page is for admins.": { es: "Esta p\u00e1gina es para administradores." },
  "This shift is open in the marketplace and available for staff to claim.": { es: "Este turno est\u00e1 abierto en el tablero y cualquier persona elegible puede tomarlo." },
  "Thu": { es: "Jue" },
  "Time": { es: "Hora" },
  "Time off": { es: "Tiempo libre" },
  "Time off ({0})": { es: "Tiempo libre ({0})" },
  "Time off approved. They get a notice in the app.": { es: "Tiempo libre aprobado. La persona recibe un aviso en la aplicaci\u00f3n." },
  "Time off denied. They get a notice in the app.": { es: "Tiempo libre denegado. La persona recibe un aviso en la aplicaci\u00f3n." },
  "Time off request": { es: "Solicitud de tiempo libre" },
  "Today": { es: "Hoy" },
  "Total": { es: "Total" },
  "Total Claimed": { es: "Total tomados" },
  "Try again": { es: "Intentar de nuevo" },
  "Tue": { es: "Mar" },
  "Type": { es: "Tipo" },
  "URGENT": { es: "URGENTE" },
  "Unassigned": { es: "Sin asignar" },
  "Until": { es: "Hasta" },
  "Upcoming": { es: "Pr\u00f3ximos" },
  "Urgency": { es: "Urgencia" },
  "Urgent": { es: "Urgente" },
  "Vendor Registry": { es: "Registro de proveedores" },
  "Vendors": { es: "Proveedores" },
  "View all": { es: "Ver todo" },
  "View shift": { es: "Ver el turno" },
  "Voluntary Drop": { es: "Baja voluntaria" },
  "Voluntary Drops": { es: "Bajas voluntarias" },
  "Wed": { es: "Mi\u00e9" },
  "Week": { es: "Semana" },
  "Weekly Trend": { es: "Tendencia semanal" },
  "Weekly pattern": { es: "Patr\u00f3n semanal" },
  "Welcome back, {0}": { es: "Bienvenido de nuevo, {0}" },
  "Welcome, {0}": { es: "Bienvenido, {0}" },
  "e.g. Marcus called out": { es: "p. ej. una persona se report\u00f3 ausente" },
  "e.g. Marcus called out sick": { es: "p. ej. una persona se report\u00f3 enferma" },
  "of {0} active": { es: "de {0} activos" },
  "{0} Admin": { es: "{0} Administraci\u00f3n" },
  "{0} Supervisor": { es: "{0} Supervisi\u00f3n" },
  "{0} added, {1} removed, {2} total": { es: "{0} agregados, {1} eliminados, {2} en total" },
  "{0} cases need attention": { es: "{0} casos necesitan atenci\u00f3n" },
  "{0} claimed with overtime risk": { es: "{0} tomados con riesgo de horas extra" },
  "{0} dates were skipped because this person is already scheduled at that time:": { es: "Se omitieron {0} fechas porque esta persona ya tiene un turno a esa hora:" },
  "{0} of {1}": { es: "{0} de {1}" },
  "{0} open issues": { es: "{0} incidencias abiertas" },
  "{0} pending": { es: "{0} pendientes" },
  "{0} unread notifications": { es: "{0} avisos sin leer" },
  "{0}% callouts": { es: "{0}% de ausencias" },
  "{0}% filled": { es: "{0}% cubierto" },
  "{0}d": { es: "{0}d" },
  "{0}h": { es: "{0}h" },
  "{0}m": { es: "{0}m" },
  // One English word, two Spanish ones. The context after the bar names the noun the Spanish
  // adjective has to agree with.
  "Active|pattern": { es: "Activo" },
  "Active|person": { es: "Activa" },
  "All|patterns": { es: "Todos" },
  "All|people": { es: "Todas" },
  "All|requests": { es: "Todas" },
  "All|shifts": { es: "Todos" },
  "All|sites": { es: "Todos" },
  "Approved|request": { es: "Aprobada" },
  "Approved|shift": { es: "Aprobado" },
  "Assigned|shift": { es: "Asignado" },
  "Assigned|task": { es: "Asignada" },
  "Cancelled|inspection": { es: "Cancelada" },
  "Cancelled|request": { es: "Cancelada" },
  "Cancelled|shift": { es: "Cancelado" },
  "Claimed|shift": { es: "Tomado" },
  "Closed|case": { es: "Cerrado" },
  "Closed|shift": { es: "Cerrado" },
  "Completed|inspection": { es: "Completada" },
  "Completed|shift": { es: "Completado" },
  "Denied|request": { es: "Denegada" },
  "Ended|pattern": { es: "Terminado" },
  "New|request": { es: "Nueva" },
  "New|shift": { es: "Nuevo" },
  "None|note": { es: "Ninguna" },
  "None|site": { es: "Ninguno" },
  "Open|issue": { es: "Abierta" },
  "Open|shift": { es: "Abierto" },
  "Released|shift": { es: "Liberado" },
  "Requested|request": { es: "Solicitada" },
  "Scheduled|inspection": { es: "Programada" },
  "Scheduled|shift": { es: "Programado" },
  // A count choice, one entry per form the language has. English has two; Spanish has two; a
  // language with more picks its own through Intl.PluralRules.
  "{0} hour|count": {
    en: { one: "{0} hour", other: "{0} hours" },
    es: { one: "{0} hora", other: "{0} horas" },
  },
  "{0} inspection|count": {
    en: { one: "{0} inspection", other: "{0} inspections" },
    es: { one: "{0} inspecci\u00f3n", other: "{0} inspecciones" },
  },
  "{0} shift claimed with overtime risk|count": {
    en: { one: "{0} shift claimed with overtime risk", other: "{0} shifts claimed with overtime risk" },
    es: { one: "{0} turno tomado con riesgo de horas extra", other: "{0} turnos tomados con riesgo de horas extra" },
  },
};

// The language the screen is being drawn in. The app sets it before anything renders and again on
// every change, the way it sets the theme, so tr() reads one value rather than taking one.
let current = "en";
export function setLang(id) { current = LOCALES.indexOf(id) >= 0 ? id : "en"; }
export function getLang() { return current; }
export function localeTag(lang) { return LOCALE_TAGS[lang || current] || LOCALE_TAGS.en; }

// What a browser says it wants, when nothing is stored.
export function browserLang() {
  try {
    const want = (navigator.languages && navigator.languages.length ? navigator.languages : [navigator.language]) || [];
    for (let i = 0; i < want.length; i += 1) {
      const two = String(want[i] || "").slice(0, 2).toLowerCase();
      if (LOCALES.indexOf(two) >= 0) return two;
    }
  } catch (e) { /* a browser that will not say is an English one */ }
  return "en";
}

const fill = (text, values) => String(text).replace(/\{(\d+)\}/g, (m, i) => {
  const v = values[Number(i)];
  return v === undefined || v === null ? "" : String(v);
});
// The text before the bar, which is the English a key falls back to.
const baseOf = (key) => { const i = String(key).lastIndexOf("|"); return i > 0 ? String(key).slice(0, i) : String(key); };

export function tr(key, ...values) {
  const entry = WORDS[key];
  const said = entry && typeof entry[current] === "string" && entry[current] !== "" ? entry[current] : null;
  return fill(said === null ? baseOf(key) : said, values);
}

const RULES = {};
function rulesFor(lang) {
  if (!RULES[lang]) {
    try { RULES[lang] = new Intl.PluralRules(localeTag(lang)); }
    catch (e) { RULES[lang] = { select: (n) => (Number(n) === 1 ? "one" : "other") }; }
  }
  return RULES[lang];
}

// A count and its word, in whichever form the language uses for that number. {0} is the count.
export function trn(key, count, ...values) {
  const entry = WORDS[key] || {};
  const pick = (forms, lang) => {
    if (!forms || typeof forms !== "object") return null;
    const form = rulesFor(lang).select(Number(count));
    return forms[form] !== undefined ? forms[form] : (forms.other !== undefined ? forms.other : null);
  };
  const said = pick(entry[current], current);
  const english = said === null ? pick(entry.en, "en") : said;
  return fill(english === null ? baseOf(key) : english, [count].concat(values));
}
