// Every word the dashboard shows, in every language it speaks.
//
// The table is keyed by the English string the code already writes, so a screen reads the same
// either way and a missing translation falls back to English rather than to a key nobody can read.
// A key can carry a context after a bar, "All|sites", because a Spanish adjective agrees with the
// noun it describes and one English word can need two Spanish ones. The fallback is the text before
// the bar, so a missing entry still reads.
//
// Spanish is written as \u escapes: every file under src/ is plain ASCII, and the accented text as
// the screen draws it lives in translation/dashboard_words.csv, which is what a translator reads
// and edits. The audit fails the run if the two ever disagree.
//
// A third language is one more key in each entry and one more id in LOCALES.
"use strict";

export const LOCALES = ["en", "es"];

// What a formatter is given. es-US rather than plain es: the company writes 1,234,567.50, and plain
// es writes 1.234.567,50.
export const LOCALE_TAGS = { en: "en-US", es: "es-US" };

// Each name is written in its own language and is never translated.
export const LANGUAGES = [
  { id: "en", label: "English" },
  { id: "es", label: "Espa\u00f1ol" },
];

export const WORDS = {
  "(use form default)": { es: "(usar la del formulario)" },
  "+ Add Document": { es: "+ Agregar documento" },
  "+ Add Other": { es: "+ Agregar otro" },
  "+ Add Training": { es: "+ Agregar capacitaci\u00f3n" },
  "+ Custom Step": { es: "+ Paso personalizado" },
  "2150000000 or name@email.com": { es: "2150000000 o nombre@correo.com" },
  "< Prev": { es: "< Anterior" },
  "A reason for reassignment is required": { es: "Se requiere un motivo para reasignar" },
  "A staff member is requesting to drop this shift.": { es: "Una persona solicita darse de baja de este turno." },
  "A staff member is requesting to drop this shift. Approve to open it for pickup, deny to keep the original assignment, or reassign directly.": { es: "Una persona solicita darse de baja de este turno. Apruebe para abrirlo a quien quiera tomarlo, deniegue para dejar la asignaci\u00f3n original, o reasigne directamente." },
  "A staff member is requesting to drop this shift. Approve to open it for pickup, or deny to keep it assigned.": { es: "Una persona solicita darse de baja de este turno. Apruebe para abrirlo a quien quiera tomarlo, o deniegue para dejarlo asignado." },
  "Actions": { es: "Acciones" },
  "Active": { es: "Activo" },
  "Active only": { es: "Solo activas" },
  "Activity Timeline": { es: "Historial de actividad" },
  "Add": { es: "Agregar" },
  "Add Custom Onboarding Step": { es: "Agregar un paso de incorporaci\u00f3n personalizado" },
  "Add Document": { es: "Agregar documento" },
  "Add Site": { es: "Agregar sitio" },
  "Add Step": { es: "Agregar el paso" },
  "Add Supply": { es: "Agregar suministro" },
  "Add Supply to Site": { es: "Agregar un suministro al sitio" },
  "Add Task": { es: "Agregar tarea" },
  "Add Training Record": { es: "Agregar un registro de capacitaci\u00f3n" },
  "Add a note saying why": { es: "Agregue una nota explicando por qu\u00e9" },
  "Add a photo": { es: "Agregar una foto" },
  "Add {0} to your home screen": { es: "Agregue {0} a su pantalla de inicio" },
  "Additional details about this shift...": { es: "Detalles adicionales sobre este turno..." },
  "Address": { es: "Direcci\u00f3n" },
  "Address *": { es: "Direcci\u00f3n *" },
  "Admin": { es: "Administrador" },
  "Admin Dashboard": { es: "Panel de administraci\u00f3n" },
  "Admin access required": { es: "Se requiere acceso de administrador" },
  "Administered By": { es: "Impartida por" },
  "Administrator": { es: "Administrador" },
  "Aliases": { es: "Alias" },
  "All ({0})": { es: "Todos ({0})" },
  "All Buildings": { es: "Todos los edificios" },
  "All Employees": { es: "Todo el personal" },
  "All Floors": { es: "Todos los pisos" },
  "All Reasons": { es: "Todos los motivos" },
  "All Sites": { es: "Todos los sitios" },
  "All Staff": { es: "Todo el personal" },
  "All Status": { es: "Todos los estados" },
  "All Zones": { es: "Todas las zonas" },
  "All current": { es: "Todo al d\u00eda" },
  "All day": { es: "Todo el d\u00eda" },
  "All people": { es: "Todas las personas" },
  "All roles": { es: "Todos los roles" },
  "All sites": { es: "Todos los sitios" },
  "All statuses": { es: "Todos los estados" },
  "All supplies are already assigned to this site": { es: "Todos los suministros ya est\u00e1n asignados a este sitio" },
  "Analytics": { es: "An\u00e1lisis" },
  "Annual": { es: "Anual" },
  "Approve": { es: "Aprobar" },
  "Approve Drop": { es: "Aprobar la baja" },
  "Approved": { es: "Aprobada" },
  "Approved Shift": { es: "Turno aprobado" },
  "Asked": { es: "Solicitado" },
  "Assign": { es: "Asignar" },
  "Assign Issue as Task": { es: "Asignar la incidencia como tarea" },
  "Assign Task": { es: "Asignar la tarea" },
  "Assign To": { es: "Asignar a" },
  "Assign To *": { es: "Asignar a *" },
  "Assign as Task": { es: "Asignar como tarea" },
  "Assigned": { es: "Asignado" },
  "Assigned Staff ({0})": { es: "Personal asignado ({0})" },
  "Assigned Supervisor": { es: "Supervisor asignado" },
  "Assigned Tasks": { es: "Tareas asignadas" },
  "Assigned To": { es: "Asignada a" },
  "Assigned to: {0}": { es: "Asignada a: {0}" },
  "Attached": { es: "Adjunto" },
  "Attached Photo": { es: "Foto adjunta" },
  "Attached Video": { es: "Video adjunto" },
  "Average": { es: "Promedio" },
  "Avg (min)": { es: "Prom. (min)" },
  "Avg Fill Time": { es: "Tiempo medio de cobertura" },
  "Avg Score": { es: "Puntaje promedio" },
  "Avg Score (30d)": { es: "Puntaje promedio (30 d)" },
  "Back to Dashboard": { es: "Volver al panel" },
  "Back to Employees": { es: "Volver al personal" },
  "Back to Sites": { es: "Volver a Sitios" },
  "Based on {0}": { es: "Seg\u00fan {0}" },
  "Benefits / Payroll": { es: "Beneficios / N\u00f3mina" },
  "Bi-Weekly": { es: "Quincenal" },
  "Billing": { es: "Facturaci\u00f3n" },
  "Bldg: {0}": { es: "Edificio: {0}" },
  "Building": { es: "Edificio" },
  "By: {0}": { es: "Por: {0}" },
  "CLAIMED": { es: "TOMADO" },
  "CSV exported": { es: "CSV exportado" },
  "Callout": { es: "Ausencia" },
  "Callout Patterns": { es: "Patrones de ausencias" },
  "Callouts": { es: "Ausencias" },
  "Cancel": { es: "Cancelar" },
  "Cancel Inspection": { es: "Cancelar la inspecci\u00f3n" },
  "Cancel ending this pattern": { es: "Cancelar el fin de este patr\u00f3n" },
  "Cancel this date": { es: "Cancelar esta fecha" },
  "Cancel this inspection?": { es: "\u00bfCancelar esta inspecci\u00f3n?" },
  "Cancel this open shift? It will no longer be available for pickup.": { es: "\u00bfCancelar este turno abierto? Ya nadie podr\u00e1 tomarlo." },
  "Cancel this shift? The pattern will not add it again.": { es: "\u00bfCancelar este turno? El patr\u00f3n no lo volver\u00e1 a agregar." },
  "Cancelled": { es: "Cancelado" },
  "Cancelled by the person who asked": { es: "Cancelada por quien la solicit\u00f3" },
  "Cases": { es: "Casos" },
  "Category": { es: "Categor\u00eda" },
  "Category is required": { es: "La categor\u00eda es obligatoria" },
  "Category updated": { es: "Categor\u00eda actualizada" },
  "Change": { es: "Cambiar" },
  "Changes start on": { es: "Los cambios comienzan el" },
  "Chat": { es: "Chat" },
  "City": { es: "Ciudad" },
  "Claimed": { es: "Tomado" },
  "Claimed By": { es: "Tomado por" },
  "Claimed Pickup Shift": { es: "Turno disponible tomado" },
  "Claims": { es: "Turnos tomados" },
  "Clear": { es: "Borrar" },
  "Click \"Create Task\" to assign one.": { es: "Haga clic en \"Crear tarea\" para asignar una." },
  "Client": { es: "Cliente" },
  "Client Contact": { es: "Contacto del cliente" },
  "Client Forms": { es: "Formularios del cliente" },
  "Client Name": { es: "Nombre del cliente" },
  "Clock": { es: "Asistencia" },
  "Close": { es: "Cerrar" },
  "Collapse sidebar": { es: "Contraer el panel lateral" },
  "Completed": { es: "Completado" },
  "Completed Date": { es: "Fecha de finalizaci\u00f3n" },
  "Completed {0}": { es: "Completado el {0}" },
  "Compliance": { es: "Cumplimiento" },
  "Confirm Convert": { es: "Confirmar la conversi\u00f3n" },
  "Confirm ending this pattern": { es: "Confirmar el fin de este patr\u00f3n" },
  "Confirm on the next screen.": { es: "Confirme en la siguiente pantalla." },
  "Connected to Live API": { es: "Conectado a la API en vivo" },
  "Contact Name": { es: "Nombre del contacto" },
  "Contract": { es: "Contrato" },
  "Contract Dates": { es: "Fechas del contrato" },
  "Contract Details": { es: "Detalles del contrato" },
  "Contract Type": { es: "Tipo de contrato" },
  "Contractor": { es: "Contratista" },
  "Conversation": { es: "Conversaci\u00f3n" },
  "Convert": { es: "Convertir" },
  "Convert Callout": { es: "Convertir la ausencia" },
  "Convert Scheduled Shift to Open Pickup": { es: "Convertir un turno programado en turno abierto" },
  "Convert to Open Pickup": { es: "Convertir en turno abierto" },
  "Copied": { es: "Copiado" },
  "Copy": { es: "Copiar" },
  "Copy the address below and paste it there.": { es: "Copie la direcci\u00f3n de abajo y p\u00e9guela all\u00ed." },
  "Could not load folder.": { es: "No se pudo cargar la carpeta." },
  "Coverage by Site": { es: "Cobertura por sitio" },
  "Create": { es: "Crear" },
  "Create Assigned Task": { es: "Crear una tarea asignada" },
  "Create Task": { es: "Crear tarea" },
  "Create and Assign": { es: "Crear y asignar" },
  "Created": { es: "Fecha de creaci\u00f3n" },
  "Created By": { es: "Creada por" },
  "Currently assigned to: {0}. They will be notified of the change.": { es: "Asignada ahora a: {0}. Recibir\u00e1 un aviso del cambio." },
  "Custodial Laborer": { es: "Auxiliar de limpieza" },
  "Custodial Lead": { es: "L\u00edder de limpieza" },
  "Custom": { es: "Personalizado" },
  "DELETE": { es: "ELIMINAR" },
  "DROP REQ": { es: "SOL. DE BAJA" },
  "Daily Checklist": { es: "Lista diaria" },
  "Dark Mode": { es: "Modo oscuro" },
  "Dark mode": { es: "Modo oscuro" },
  "Dashboard": { es: "Panel" },
  "Date": { es: "Fecha" },
  "Date *": { es: "Fecha *" },
  "Date is required": { es: "La fecha es obligatoria" },
  "Dates": { es: "Fechas" },
  "Day Porter": { es: "Conserje de d\u00eda" },
  "Days": { es: "D\u00edas" },
  "Deactivate": { es: "Desactivar" },
  "Deactivate this site?": { es: "\u00bfDesactivar este sitio?" },
  "Decided": { es: "Decidido" },
  "Decided by": { es: "Decidido por" },
  "Deciding this request leaves these shifts as they are. Change or cover them on the schedule.": { es: "Decidir esta solicitud deja estos turnos como est\u00e1n. C\u00e1mbielos o c\u00fabralos en el horario." },
  "Delete": { es: "Eliminar" },
  "Delete Permanently": { es: "Eliminar de forma permanente" },
  "Delete this document?": { es: "\u00bfEliminar este documento?" },
  "Delete this scheduled shift? This cannot be undone.": { es: "\u00bfEliminar este turno programado? Esta acci\u00f3n no se puede deshacer." },
  "Delete this step?": { es: "\u00bfEliminar este paso?" },
  "Delete this training record?": { es: "\u00bfEliminar este registro de capacitaci\u00f3n?" },
  "Denied": { es: "Denegada" },
  "Deny": { es: "Denegar" },
  "Deny Request": { es: "Denegar la solicitud" },
  "Describe what happened": { es: "Describa qu\u00e9 pas\u00f3" },
  "Description *": { es: "Descripci\u00f3n *" },
  "Detailed Instructions": { es: "Instrucciones detalladas" },
  "Detailed Instructions (optional)": { es: "Instrucciones detalladas (opcional)" },
  "Document": { es: "Documento" },
  "Document added": { es: "Documento agregado" },
  "Document deleted": { es: "Documento eliminado" },
  "Document not found": { es: "No se encontr\u00f3 el documento" },
  "Document the scope of work for this site...": { es: "Documente el alcance del trabajo de este sitio..." },
  "Document updated": { es: "Documento actualizado" },
  "Documents": { es: "Documentos" },
  "Don't show again": { es: "No volver a mostrar" },
  "Done": { es: "Listo" },
  "Drop Req": { es: "Sol. de baja" },
  "Drop Request": { es: "Solicitud de baja" },
  "Drop Requested": { es: "Baja solicitada" },
  "Drop Requests": { es: "Solicitudes de baja" },
  "Drop approved": { es: "Baja aprobada" },
  "Drop approved, shift is now open": { es: "Baja aprobada, el turno queda abierto" },
  "Drop approved, shift is open": { es: "Baja aprobada, el turno queda abierto" },
  "Drop request denied": { es: "Solicitud de baja denegada" },
  "Due Date": { es: "Fecha l\u00edmite" },
  "Due Time": { es: "Hora l\u00edmite" },
  "Due: {0}": { es: "Vence: {0}" },
  "Edit": { es: "Editar" },
  "Edit Details": { es: "Editar los detalles" },
  "Edit Document": { es: "Editar el documento" },
  "Edit Scheduled Shift": { es: "Editar el turno programado" },
  "Edit Site Details": { es: "Editar los detalles del sitio" },
  "Edit Task": { es: "Editar la tarea" },
  "Edit Training Record": { es: "Editar el registro de capacitaci\u00f3n" },
  "Email": { es: "Correo" },
  "Employee": { es: "Persona" },
  "Employee is required": { es: "La persona es obligatoria" },
  "Employee, name, and type are required": { es: "La persona, el nombre y el tipo son obligatorios" },
  "Employees": { es: "Personal" },
  "Empty": { es: "Vac\u00edo" },
  "End": { es: "Fin" },
  "End Date": { es: "Fecha de fin" },
  "End Time": { es: "Hora de fin" },
  "End Time *": { es: "Hora de fin *" },
  "End pattern": { es: "Terminar el patr\u00f3n" },
  "End this pattern after": { es: "Terminar este patr\u00f3n despu\u00e9s del" },
  "End this pattern after {0}? Future shifts it added are removed, except ones changed by hand.": { es: "\u00bfTerminar este patr\u00f3n despu\u00e9s del {0}? Los turnos futuros que agreg\u00f3 se eliminan, salvo los que se cambiaron a mano." },
  "End time": { es: "Hora de fin" },
  "Ended": { es: "Terminado" },
  "Ends": { es: "Termina" },
  "Enter": { es: "Ingrese" },
  "Everyone": { es: "Todos" },
  "Expand sidebar": { es: "Ampliar el panel lateral" },
  "Expired Docs": { es: "Docs. vencidos" },
  "Expired Documents": { es: "Documentos vencidos" },
  "Expired Items": { es: "Elementos vencidos" },
  "Expired Training": { es: "Capacitaciones vencidas" },
  "Expires in {0}d": { es: "Vence en {0} d" },
  "Expires {0}d": { es: "Vence en {0} d" },
  "Expiring (30 days)": { es: "Por vencer (30 d\u00edas)" },
  "Expiring (30d)": { es: "Por vencer (30 d)" },
  "Expiring Within 30 Days": { es: "Vencen en los pr\u00f3ximos 30 d\u00edas" },
  "Expiry": { es: "Vencimiento" },
  "Expiry Date": { es: "Fecha de vencimiento" },
  "Expiry Date (optional)": { es: "Fecha de vencimiento (opcional)" },
  "Explain why this is being reassigned...": { es: "Explique por qu\u00e9 se reasigna..." },
  "Explain why this task is being reassigned...": { es: "Explique por qu\u00e9 se reasigna esta tarea..." },
  "Export CSV": { es: "Exportar CSV" },
  "Extra Coverage": { es: "Cobertura adicional" },
  "Extra large": { es: "Muy grande" },
  "Failed to load supplies": { es: "No se pudieron cargar los suministros" },
  "Fastest": { es: "M\u00e1s r\u00e1pido" },
  "File": { es: "Archivo" },
  "File fetch failed ({0}): {1}": { es: "No se pudo obtener el archivo ({0}): {1}" },
  "File must be under 50MB": { es: "El archivo debe pesar menos de 50 MB" },
  "Fill Rate": { es: "Tasa de cobertura" },
  "Fill Rate by Reason": { es: "Tasa de cobertura por motivo" },
  "Filled through {0}": { es: "Cubierto hasta el {0}" },
  "First Name A-Z": { es: "Nombre A-Z" },
  "Fl {0}": { es: "Piso {0}" },
  "Floor": { es: "Piso" },
  "Floor Plans ({0})": { es: "Planos ({0})" },
  "Floor plan removed": { es: "Plano quitado" },
  "Floor plan uploaded": { es: "Plano subido" },
  "Floor {0}": { es: "Piso {0}" },
  "Floor: {0}": { es: "Piso: {0}" },
  "For": { es: "Por" },
  "Form default: {0}": { es: "Del formulario: {0}" },
  "Forms": { es: "Formularios" },
  "Fri": { es: "Vie" },
  "F{0}": { es: "P{0}" },
  "General": { es: "General" },
  "General Info": { es: "Informaci\u00f3n general" },
  "Green": { es: "Ecol\u00f3gico" },
  "Green Buildings": { es: "Edificios sostenibles" },
  "HR - Onboarding": { es: "RR. HH. - Incorporaci\u00f3n" },
  "HR - Ongoing / Annual": { es: "RR. HH. - Continuo / Anual" },
  "HR Records": { es: "Expedientes de personal" },
  "Has details": { es: "Tiene detalles" },
  "Health, Safety & Environment": { es: "Salud, seguridad y medio ambiente" },
  "Help": { es: "Ayuda" },
  "Hide": { es: "Ocultar" },
  "Hide manual entry": { es: "Ocultar la entrada manual" },
  "Hide test accounts": { es: "Ocultar las cuentas de prueba" },
  "Hire Date (newest)": { es: "Fecha de contrataci\u00f3n (m\u00e1s reciente)" },
  "Hire Date (oldest)": { es: "Fecha de contrataci\u00f3n (m\u00e1s antigua)" },
  "Hired {0}": { es: "Contrataci\u00f3n: {0}" },
  "Hours": { es: "Horas" },
  "Human Resources": { es: "Recursos humanos" },
  "In Progress": { es: "En curso" },
  "Inactive only": { es: "Solo inactivas" },
  "Inheriting form's category. Pick a value to override.": { es: "Usa la categor\u00eda del formulario. Elija un valor para cambiarla." },
  "Initialize Onboarding": { es: "Iniciar la incorporaci\u00f3n" },
  "Inspection": { es: "Inspecci\u00f3n" },
  "Inspection Details": { es: "Detalles de la inspecci\u00f3n" },
  "Inspection cancelled": { es: "Inspecci\u00f3n cancelada" },
  "Inspection rescheduled": { es: "Inspecci\u00f3n reprogramada" },
  "Inspection scores by site": { es: "Puntajes de inspecci\u00f3n por sitio" },
  "Inspections": { es: "Inspecciones" },
  "Inspections (Last 30 Days)": { es: "Inspecciones (\u00faltimos 30 d\u00edas)" },
  "Install": { es: "Instalar" },
  "Integrations": { es: "Integraciones" },
  "Inventory": { es: "Inventario" },
  "Issue": { es: "Incidencia" },
  "Issue Detail": { es: "Detalle de la incidencia" },
  "Issue Tracker": { es: "Registro de incidencias" },
  "Issues": { es: "Incidencias" },
  "It opens like an app, one tap from your home screen.": { es: "Se abre como una aplicaci\u00f3n, a un toque desde su pantalla de inicio." },
  "Jotform Form": { es: "Formulario de Jotform" },
  "Jotform Reference": { es: "Referencia de Jotform" },
  "Jotform Submission (optional)": { es: "Env\u00edo de Jotform (opcional)" },
  "Jotform is not configured. Use the manual entry below.": { es: "Jotform no est\u00e1 configurado. Use la entrada manual de abajo." },
  "Jotform submission ID or URL": { es: "ID o enlace del env\u00edo de Jotform" },
  "LIVE": { es: "EN VIVO" },
  "Label": { es: "Nombre" },
  "Label and zone required": { es: "La descripci\u00f3n y la zona son obligatorias" },
  "Language": { es: "Idioma" },
  "Large": { es: "Grande" },
  "Largest": { es: "M\u00e1ximo" },
  "Last 30 Days": { es: "\u00daltimos 30 d\u00edas" },
  "Last 90 Days": { es: "\u00daltimos 90 d\u00edas" },
  "Last Inspection": { es: "\u00daltima inspecci\u00f3n" },
  "Last Name A-Z": { es: "Apellido A-Z" },
  "Last Name Z-A": { es: "Apellido Z-A" },
  "Last Week": { es: "La semana pasada" },
  "Last activity": { es: "\u00daltima actividad" },
  "Last day": { es: "\u00daltimo d\u00eda" },
  "Legal / Consent": { es: "Legal / Consentimiento" },
  "Light Mode": { es: "Modo claro" },
  "Light mode": { es: "Modo claro" },
  "Live Operations": { es: "Operaciones en vivo" },
  "Live Ops": { es: "Operaciones en vivo" },
  "Load More": { es: "Ver m\u00e1s" },
  "Load more": { es: "Ver m\u00e1s" },
  "Loading buildings...": { es: "Cargando los edificios..." },
  "Loading folder...": { es: "Cargando la carpeta..." },
  "Loading patterns...": { es: "Cargando los patrones..." },
  "Loading schedule...": { es: "Cargando el horario..." },
  "Loading submissions...": { es: "Cargando los env\u00edos..." },
  "Loading time off...": { es: "Cargando el tiempo libre..." },
  "Loading...": { es: "Cargando..." },
  "Logout": { es: "Cerrar sesi\u00f3n" },
  "Management Commitment": { es: "Compromiso de la direcci\u00f3n" },
  "Mark all read": { es: "Marcar todo como le\u00eddo" },
  "Marketplace": { es: "Tablero" },
  "Marketplace Coverage (Last 30 Days)": { es: "Cobertura en el tablero (\u00faltimos 30 d\u00edas)" },
  "Median": { es: "Mediana" },
  "Median (min)": { es: "Mediana (min)" },
  "Messages": { es: "Mensajes" },
  "Min: {0}": { es: "M\u00edn.: {0}" },
  "Mon": { es: "Lun" },
  "Month": { es: "Mes" },
  "Monthly": { es: "Mensual" },
  "Monthly Totals": { es: "Totales del mes" },
  "Monthly Value": { es: "Valor mensual" },
  "Monthly Value ($)": { es: "Valor mensual ($)" },
  "Most Recent Activity": { es: "Actividad m\u00e1s reciente" },
  "Most recent inspection per site": { es: "Inspecci\u00f3n m\u00e1s reciente por sitio" },
  "N/A": { es: "N/D" },
  "Name": { es: "Nombre" },
  "Name *": { es: "Nombre *" },
  "Name and address required": { es: "El nombre y la direcci\u00f3n son obligatorios" },
  "Name and category are required": { es: "El nombre y la categor\u00eda son obligatorios" },
  "New Shift": { es: "Turno nuevo" },
  "New Shifts": { es: "Turnos nuevos" },
  "Next": { es: "Siguiente" },
  "Next >": { es: "Siguiente >" },
  "Next Week": { es: "La pr\u00f3xima semana" },
  "No HR records on file for this employee yet.": { es: "Todav\u00eda no hay expedientes de personal para esta persona." },
  "No Show": { es: "No se present\u00f3" },
  "No activity recorded for this site": { es: "No hay actividad registrada para este sitio" },
  "No assigned tasks found.": { es: "No se encontraron tareas asignadas." },
  "No buildings configured": { es: "No hay edificios configurados" },
  "No checklist initialized": { es: "No se ha iniciado la lista" },
  "No conversations.": { es: "No hay conversaciones." },
  "No data to export": { es: "No hay datos para exportar" },
  "No data to print": { es: "No hay datos para imprimir" },
  "No documents found. Use Add Document to upload.": { es: "No se encontraron documentos. Use Agregar documento para subir uno." },
  "No documents match this search.": { es: "Ning\u00fan documento coincide con la b\u00fasqueda." },
  "No employees match your filters.": { es: "Ninguna persona coincide con los filtros." },
  "No end": { es: "Sin fin" },
  "No end date": { es: "Sin fecha de fin" },
  "No file": { es: "Sin archivo" },
  "No inspections recorded yet.": { es: "Todav\u00eda no hay inspecciones registradas." },
  "No items filed under Other. Use Add Other to upload.": { es: "No hay nada archivado en Otros. Use Agregar otro para subir algo." },
  "No items in this category.": { es: "No hay elementos en esta categor\u00eda." },
  "No items match this search.": { es: "Ning\u00fan elemento coincide con la b\u00fasqueda." },
  "No matching pages": { es: "Ninguna p\u00e1gina coincide" },
  "No messages in this site channel": { es: "No hay mensajes en el canal de este sitio" },
  "No messages to print": { es: "No hay mensajes para imprimir" },
  "No messages yet": { es: "Todav\u00eda no hay mensajes" },
  "No messages yet.": { es: "Todav\u00eda no hay mensajes." },
  "No note": { es: "Sin nota" },
  "No patterns yet. Turn on Repeat when adding a shift to create one.": { es: "Todav\u00eda no hay patrones. Active Repetir al agregar un turno para crear uno." },
  "No pickup activity found in this period.": { es: "No hay actividad de turnos disponibles en este periodo." },
  "No reason given": { es: "Sin motivo" },
  "No records match this search.": { es: "Ning\u00fan registro coincide con la b\u00fasqueda." },
  "No role": { es: "Sin rol" },
  "No scope of work documented yet.": { es: "Todav\u00eda no se ha documentado el alcance del trabajo." },
  "No shift started on {0} ({1})": { es: "Sin turno iniciado el {0} ({1})" },
  "No shift started today ({0})": { es: "Sin turno iniciado hoy ({0})" },
  "No shifts found for this period and filter.": { es: "No hay turnos en este periodo con este filtro." },
  "No shifts on these days.": { es: "No hay turnos en estos d\u00edas." },
  "No shifts started on {0}.": { es: "Ning\u00fan turno iniciado el {0}." },
  "No shifts started yet today.": { es: "Todav\u00eda no ha iniciado ning\u00fan turno hoy." },
  "No sites found.": { es: "No se encontraron sitios." },
  "No specific service": { es: "Ning\u00fan servicio en particular" },
  "No staff assigned": { es: "No hay personal asignado" },
  "No staff match that search": { es: "Ninguna persona coincide con esa b\u00fasqueda" },
  "No supplies assigned to this site": { es: "No hay suministros asignados a este sitio" },
  "No tasks configured for this site": { es: "No hay tareas configuradas para este sitio" },
  "No training records found.": { es: "No se encontraron registros de capacitaci\u00f3n." },
  "No unlinked Jotform submissions for this employee. Sync the Forms page if needed, or use manual entry.": { es: "Esta persona no tiene env\u00edos de Jotform sin vincular. Sincronice la p\u00e1gina Formularios si hace falta, o use la entrada manual." },
  "No upcoming scheduled shifts found.": { es: "No hay turnos programados pr\u00f3ximos." },
  "No upcoming shifts": { es: "No hay pr\u00f3ximos turnos" },
  "No-Show": { es: "No se present\u00f3" },
  "No-Shows": { es: "No se presentaron" },
  "Normal": { es: "Normal" },
  "Not given": { es: "No indicado" },
  "Not now": { es: "Ahora no" },
  "Not sent.": { es: "No se envi\u00f3." },
  "Note": { es: "Nota" },
  "Note to previous assignee (optional)": { es: "Nota para quien la ten\u00eda asignada (opcional)" },
  "Notes": { es: "Notas" },
  "Notes (optional)": { es: "Notas (opcional)" },
  "Nothing changed yet.": { es: "Nada ha cambiado todav\u00eda." },
  "Nothing yet.": { es: "Nada todav\u00eda." },
  "Notifications": { es: "Avisos" },
  "Notifications did not load.": { es: "Los avisos no se cargaron." },
  "OPEN": { es: "ABIERTO" },
  "OT Risk": { es: "Riesgo de horas extra" },
  "Oldest Activity": { es: "Actividad m\u00e1s antigua" },
  "Onboarding": { es: "Incorporaci\u00f3n" },
  "Onboarding Progress": { es: "Avance de la incorporaci\u00f3n" },
  "Onboarding Step": { es: "Paso de incorporaci\u00f3n" },
  "Onboarding incomplete": { es: "Incorporaci\u00f3n incompleta" },
  "Onboarding initialized": { es: "Incorporaci\u00f3n iniciada" },
  "Onboarding {0}/{1}": { es: "Incorporaci\u00f3n {0}/{1}" },
  "One-Off Assigned": { es: "Asignada una sola vez" },
  "Open": { es: "Abierto" },
  "Open Issues": { es: "Incidencias abiertas" },
  "Open Marketplace Shift": { es: "Turno abierto en el tablero" },
  "Open Now": { es: "Abiertos ahora" },
  "Open file": { es: "Abrir el archivo" },
  "Open shift posted": { es: "Turno abierto publicado" },
  "Open that pattern": { es: "Abrir ese patr\u00f3n" },
  "Open the browser menu (the three dots).": { es: "Abra el men\u00fa del navegador (los tres puntos)." },
  "Open the pattern": { es: "Abrir el patr\u00f3n" },
  "Open this page in Safari or Chrome first.": { es: "Abra esta p\u00e1gina primero en Safari o Chrome." },
  "Operational": { es: "Operativo" },
  "Operations": { es: "Operaciones" },
  "Operations overview.": { es: "Resumen de operaciones." },
  "Optional notes": { es: "Notas opcionales" },
  "Optional when approving. Required when denying.": { es: "Opcional al aprobar. Obligatoria al denegar." },
  "Or enter manually": { es: "O escr\u00edbala a mano" },
  "Original": { es: "Original" },
  "Originally Assigned": { es: "Asignado originalmente" },
  "Other": { es: "Otro" },
  "Override active. Pick blank to revert to form default.": { es: "Categor\u00eda cambiada a mano. Elija la opci\u00f3n en blanco para volver a la del formulario." },
  "Overtime risk: claiming this shift may push the worker past 40 weekly hours.": { es: "Riesgo de horas extra: tomar este turno puede llevar a la persona a m\u00e1s de 40 horas semanales." },
  "Overview": { es: "Resumen" },
  "PDF fetch failed ({0}): {1}": { es: "No se pudo obtener el PDF ({0}): {1}" },
  "PDF is being captured, check back in a few minutes.": { es: "Se est\u00e1 capturando el PDF. Vuelva a revisar en unos minutos." },
  "PIN": { es: "PIN" },
  "Page {0}": { es: "P\u00e1gina {0}" },
  "Page {0} / {1}": { es: "P\u00e1gina {0} / {1}" },
  "Part of a weekly pattern. Changes here apply to this date only.": { es: "Parte de un patr\u00f3n semanal. Los cambios aqu\u00ed se aplican solo a esta fecha." },
  "Paste a URL or upload below": { es: "Pegue un enlace o suba un archivo abajo" },
  "Pattern saved. {0} shifts added through {1}.": { es: "Patr\u00f3n guardado. {0} turnos agregados hasta el {1}." },
  "Patterns": { es: "Patrones" },
  "Pending": { es: "Pendiente" },
  "Permanently Delete Site": { es: "Eliminar el sitio de forma permanente" },
  "Person": { es: "Persona" },
  "Phone": { es: "Tel\u00e9fono" },
  "Phone or Email": { es: "Tel\u00e9fono o correo" },
  "Photo": { es: "Foto" },
  "Photo Added": { es: "Foto agregada" },
  "Photo Attached": { es: "Foto adjunta" },
  "Photo attached": { es: "Foto adjunta" },
  "Photo {0}": { es: "Foto {0}" },
  "Photo/Video": { es: "Foto o video" },
  "Photo/Video (optional)": { es: "Foto o video (opcional)" },
  "Photos ({0})": { es: "Fotos ({0})" },
  "Pick a conversation on the left to start.": { es: "Elija una conversaci\u00f3n a la izquierda para empezar." },
  "Pickup": { es: "Turno disponible" },
  "Pickup Shift": { es: "Turno disponible" },
  "Please choose a file to upload": { es: "Elija un archivo para subir" },
  "Post Open Shift": { es: "Publicar turno abierto" },
  "Post Shift": { es: "Publicar turno" },
  "Prev": { es: "Anterior" },
  "Prime Contractor": { es: "Contratista principal" },
  "Print": { es: "Imprimir" },
  "Priority": { es: "Prioridad" },
  "Private conversations": { es: "Conversaciones privadas" },
  "Private message": { es: "Mensaje privado" },
  "Quality": { es: "Calidad" },
  "Quality System": { es: "Sistema de calidad" },
  "Quarterly": { es: "Trimestral" },
  "Reactivate": { es: "Reactivar" },
  "Reason": { es: "Motivo" },
  "Reason Breakdown": { es: "Desglose por motivo" },
  "Reason for Reassignment *": { es: "Motivo de la reasignaci\u00f3n *" },
  "Reassign": { es: "Reasignar" },
  "Reassign Issue": { es: "Reasignar la incidencia" },
  "Reassign Task": { es: "Reasignar la tarea" },
  "Reassign To": { es: "Reasignar a" },
  "Reassign To *": { es: "Reasignar a *" },
  "Reassigned": { es: "Reasignada" },
  "Record Detail": { es: "Detalle del registro" },
  "Record Fields": { es: "Campos del registro" },
  "Recorded when the person started the shift in the portal. There is no end time and no hours here.": { es: "Registrado cuando la persona inici\u00f3 el turno en el portal. Aqu\u00ed no hay hora de fin ni horas." },
  "Records": { es: "Registros" },
  "Refresh": { es: "Actualizar" },
  "Related Items ({0})": { es: "Elementos relacionados ({0})" },
  "Release": { es: "Liberar" },
  "Release this shift back to the open pool?": { es: "\u00bfLiberar este turno y devolverlo a los turnos abiertos?" },
  "Released": { es: "Liberado" },
  "Reliability": { es: "Cumplimiento" },
  "Remove": { es: "Quitar" },
  "Remove photo": { es: "Quitar la foto" },
  "Remove this floor plan?": { es: "\u00bfQuitar este plano?" },
  "Remove this supply from the site?": { es: "\u00bfQuitar este suministro del sitio?" },
  "Repeat on": { es: "Repetir los" },
  "Repeat this shift": { es: "Repetir este turno" },
  "Repeats": { es: "Se repite" },
  "Replaces an earlier pattern": { es: "Reemplaza a un patr\u00f3n anterior" },
  "Report": { es: "Informe" },
  "Report in progress": { es: "Informe en curso" },
  "Report submitted.": { es: "Informe enviado." },
  "Reported": { es: "Reportada" },
  "Reported At": { es: "Fecha del reporte" },
  "Reported By": { es: "Reportada por" },
  "Reports": { es: "Informes" },
  "Request denied": { es: "Solicitud denegada" },
  "Request failed": { es: "La solicitud fall\u00f3" },
  "Requested": { es: "Solicitado" },
  "Requested By": { es: "Solicitado por" },
  "Requests": { es: "Solicitudes" },
  "Reschedule": { es: "Reprogramar" },
  "Resolution": { es: "Resoluci\u00f3n" },
  "Resolution Photo": { es: "Foto de la resoluci\u00f3n" },
  "Resolution: {0}": { es: "Resoluci\u00f3n: {0}" },
  "Resolve": { es: "Resolver" },
  "Resolved": { es: "Resuelta" },
  "Resolved At": { es: "Fecha de resoluci\u00f3n" },
  "Response Time": { es: "Tiempo de respuesta" },
  "Response Time Summary": { es: "Resumen del tiempo de respuesta" },
  "Response Time by Site": { es: "Tiempo de respuesta por sitio" },
  "Response Time by Urgency": { es: "Tiempo de respuesta por urgencia" },
  "Resume": { es: "Continuar" },
  "Retry": { es: "Reintentar" },
  "Role": { es: "Rol" },
  "Safety / Incident": { es: "Seguridad / Incidente" },
  "Sat": { es: "S\u00e1b" },
  "Save": { es: "Guardar" },
  "Save Changes": { es: "Guardar los cambios" },
  "Save Scope": { es: "Guardar el alcance" },
  "Save changes": { es: "Guardar los cambios" },
  "Saved": { es: "Guardado" },
  "Schedule": { es: "Horario" },
  "Schedule All": { es: "Programar todo" },
  "Schedule Shift": { es: "Programar turno" },
  "Schedule updated": { es: "Horario actualizado" },
  "Scheduled": { es: "Programado" },
  "Scheduled Date *": { es: "Fecha programada *" },
  "Scheduling for": { es: "Programando para" },
  "Scope of Work": { es: "Alcance del trabajo" },
  "Score": { es: "Puntaje" },
  "Scroll down and tap Add to Home Screen.": { es: "Despl\u00e1cese hacia abajo y toque Agregar a pantalla de inicio." },
  "Search employee, category, file, uploaded by": { es: "Buscar persona, categor\u00eda, archivo o qui\u00e9n lo subi\u00f3" },
  "Search employee, file, notes": { es: "Buscar persona, archivo o notas" },
  "Search employee, training, type, administered by": { es: "Buscar persona, capacitaci\u00f3n, tipo o qui\u00e9n la imparti\u00f3" },
  "Search name, email, or role...": { es: "Buscar por nombre, correo o rol..." },
  "Search pages": { es: "Buscar p\u00e1ginas" },
  "Search site, address, contract": { es: "Buscar sitio, direcci\u00f3n o contrato" },
  "Search site, service, staff, notes": { es: "Buscar por sitio, servicio, personal o notas" },
  "Search staff": { es: "Buscar personal" },
  "Search staff...": { es: "Buscar personal..." },
  "Select (optional)": { es: "Seleccione (opcional)" },
  "Select a scheduled shift below. The original shift will be cancelled and replaced with an open pickup that eligible staff can claim.": { es: "Seleccione un turno programado abajo. El turno original se cancela y se reemplaza por un turno abierto que el personal elegible puede tomar." },
  "Select a staff member": { es: "Seleccione a una persona" },
  "Select a staff member...": { es: "Seleccione a una persona..." },
  "Select a synced submission...": { es: "Seleccione un env\u00edo sincronizado..." },
  "Select an employee first": { es: "Primero seleccione a una persona" },
  "Select an employee first to see matching Jotform submissions.": { es: "Primero seleccione a una persona para ver sus env\u00edos de Jotform." },
  "Select an employee to view their onboarding checklist.": { es: "Seleccione a una persona para ver su lista de incorporaci\u00f3n." },
  "Select building...": { es: "Seleccione un edificio..." },
  "Select category...": { es: "Seleccione una categor\u00eda..." },
  "Select employee...": { es: "Seleccione a una persona..." },
  "Select floor...": { es: "Seleccione un piso..." },
  "Select site...": { es: "Seleccione un sitio..." },
  "Select staff member...": { es: "Seleccione a la persona..." },
  "Select staff...": { es: "Seleccione personal..." },
  "Select type...": { es: "Seleccione un tipo..." },
  "Select...": { es: "Seleccione..." },
  "Send": { es: "Enviar" },
  "Service": { es: "Servicio" },
  "Service Catalog": { es: "Cat\u00e1logo de servicios" },
  "Service Category": { es: "Categor\u00eda de servicio" },
  "Service Delivery": { es: "Prestaci\u00f3n del servicio" },
  "Service Details": { es: "Detalles del servicio" },
  "Service category": { es: "Categor\u00eda de servicio" },
  "Services": { es: "Servicios" },
  "Session expired": { es: "La sesi\u00f3n expir\u00f3" },
  "Settings": { es: "Configuraci\u00f3n" },
  "Share button": { es: "bot\u00f3n Compartir" },
  "Shift": { es: "Turno" },
  "Shift Details": { es: "Detalles del turno" },
  "Shift Drop Request": { es: "Solicitud de baja de turno" },
  "Shift Pickup": { es: "Turnos disponibles" },
  "Shift Pickup Board": { es: "Tablero de turnos disponibles" },
  "Shift approved": { es: "Turno aprobado" },
  "Shift assigned": { es: "Turno asignado" },
  "Shift cancelled": { es: "Turno cancelado" },
  "Shift converted to open pickup": { es: "Turno convertido en turno abierto" },
  "Shift reassigned": { es: "Turno reasignado" },
  "Shift released": { es: "Turno liberado" },
  "Shift removed": { es: "Turno eliminado" },
  "Shift scheduled": { es: "Turno programado" },
  "Shift updated": { es: "Turno actualizado" },
  "Shifts": { es: "Turnos" },
  "Shifts & Schedule": { es: "Turnos y horario" },
  "Shifts before this date stay as they are. Shifts someone changed or cancelled by hand are kept.": { es: "Los turnos anteriores a esta fecha quedan como est\u00e1n. Los turnos que alguien cambi\u00f3 o cancel\u00f3 a mano se conservan." },
  "Shifts by Day of Week": { es: "Turnos por d\u00eda de la semana" },
  "Shifts on these days": { es: "Turnos en estos d\u00edas" },
  "Show": { es: "Mostrar" },
  "Show test accounts": { es: "Mostrar las cuentas de prueba" },
  "Showing the first {0}. Choose a person to narrow the list.": { es: "Mostrando los primeros {0}. Elija una persona para acotar la lista." },
  "Showing {0} to {1} of {2}": { es: "Mostrando {0} a {1} de {2}" },
  "Sign In": { es: "Iniciar sesi\u00f3n" },
  "Sign Out": { es: "Cerrar sesi\u00f3n" },
  "Signing in...": { es: "Iniciando sesi\u00f3n..." },
  "Since midnight": { es: "Desde la medianoche" },
  "Site": { es: "Sitio" },
  "Site *": { es: "Sitio *" },
  "Site Channel Messages": { es: "Mensajes del canal del sitio" },
  "Site Name": { es: "Nombre del sitio" },
  "Site Notes": { es: "Notas del sitio" },
  "Site created": { es: "Sitio creado" },
  "Site deactivated": { es: "Sitio desactivado" },
  "Site permanently deleted": { es: "Sitio eliminado de forma permanente" },
  "Site reactivated": { es: "Sitio reactivado" },
  "Site updated": { es: "Sitio actualizado" },
  "Site x Day Heatmap": { es: "Mapa de calor de sitio por d\u00eda" },
  "Site, date, and times are required": { es: "El sitio, la fecha y las horas son obligatorios" },
  "Site, description, zone, and assignee are required": { es: "El sitio, la descripci\u00f3n, la zona y la persona asignada son obligatorios" },
  "Sites": { es: "Sitios" },
  "Slowest": { es: "M\u00e1s lento" },
  "Someone else has to decide your own request.": { es: "Otra persona tiene que decidir su propia solicitud." },
  "Soonest first. Deciding a request leaves the schedule as it is.": { es: "Primero las m\u00e1s pr\u00f3ximas. Decidir una solicitud deja el horario como est\u00e1." },
  "Source record not found. The original data may have been deleted.": { es: "No se encontr\u00f3 el registro de origen. Es posible que los datos originales se hayan eliminado." },
  "Staff": { es: "Personal" },
  "Staff Management": { es: "Gesti\u00f3n de personal" },
  "Staff Member": { es: "Persona" },
  "Staff Member *": { es: "Persona *" },
  "Staff Reliability": { es: "Cumplimiento del personal" },
  "Staff Reliability Metrics": { es: "Indicadores de cumplimiento del personal" },
  "Staff Summary": { es: "Resumen del personal" },
  "Staff at this site...": { es: "Personal de este sitio..." },
  "Staff with Onboarding": { es: "Personal en incorporaci\u00f3n" },
  "Staff, site, start time, and end time are required": { es: "La persona, el sitio, la hora de inicio y la hora de fin son obligatorios" },
  "Standard": { es: "Est\u00e1ndar" },
  "Start": { es: "Inicio" },
  "Start Date": { es: "Fecha de inicio" },
  "Start Time": { es: "Hora de inicio" },
  "Start Time *": { es: "Hora de inicio *" },
  "Start Work": { es: "Iniciar el trabajo" },
  "Start time": { es: "Hora de inicio" },
  "Started": { es: "Iniciado" },
  "Started Shift": { es: "Turno iniciado" },
  "Started on {0}": { es: "Iniciados el {0}" },
  "Started today": { es: "Iniciados hoy" },
  "Starts": { es: "Comienza" },
  "State": { es: "Estado" },
  "Status": { es: "Estado" },
  "Status Changed": { es: "Cambio de estado" },
  "Step Name": { es: "Nombre del paso" },
  "Step added": { es: "Paso agregado" },
  "Step deleted": { es: "Paso eliminado" },
  "Step-by-step instructions or notes...": { es: "Instrucciones paso a paso o notas..." },
  "Step-by-step instructions, tips, or notes for the cleaner...": { es: "Instrucciones paso a paso, consejos o notas para quien limpia..." },
  "Step-by-step instructions, tips, or notes...": { es: "Instrucciones paso a paso, consejos o notas..." },
  "Still needed before you can submit:": { es: "Falta esto antes de poder enviarlo:" },
  "Stock: {0}": { es: "Existencias: {0}" },
  "Submit report": { es: "Enviar el informe" },
  "Submitting...": { es: "Enviando..." },
  "Sun": { es: "Dom" },
  "Supervisor": { es: "Supervisor" },
  "Supplies": { es: "Suministros" },
  "Supplies & Inventory": { es: "Suministros e inventario" },
  "Supplies at This Site ({0})": { es: "Suministros en este sitio ({0})" },
  "Supply assigned": { es: "Suministro asignado" },
  "Supply removed": { es: "Suministro quitado" },
  "System": { es: "Sistema" },
  "TEST": { es: "PRUEBA" },
  "Tap Add or Install.": { es: "Toque Agregar o Instalar." },
  "Tap Add to Home Screen.": { es: "Toque Agregar a pantalla de inicio." },
  "Tap Add to Home screen or Install app.": { es: "Toque Agregar a pantalla de inicio o Instalar aplicaci\u00f3n." },
  "Tap Add.": { es: "Toque Agregar." },
  "Tap Install below.": { es: "Toque Instalar abajo." },
  "Tap the Share button at the bottom of the screen.": { es: "Toque el bot\u00f3n Compartir en la parte inferior de la pantalla." },
  "Tap the Share button in the address bar.": { es: "Toque el bot\u00f3n Compartir en la barra de direcciones." },
  "Task": { es: "Tarea" },
  "Task Description *": { es: "Descripci\u00f3n de la tarea *" },
  "Task Detail": { es: "Detalle de la tarea" },
  "Task Name": { es: "Nombre de la tarea" },
  "Task Type": { es: "Tipo de tarea" },
  "Task created": { es: "Tarea creada" },
  "Task created and assigned": { es: "Tarea creada y asignada" },
  "Task progress": { es: "Avance de tareas" },
  "Task reassigned": { es: "Tarea reasignada" },
  "Task reference": { es: "Referencia de la tarea" },
  "Task updated": { es: "Tarea actualizada" },
  "Tasks": { es: "Tareas" },
  "Tasks ({0})": { es: "Tareas ({0})" },
  "Tax Forms": { es: "Formularios de impuestos" },
  "Tell me what happened and I will tell you what to do.": { es: "Cu\u00e9nteme qu\u00e9 pas\u00f3 y le digo qu\u00e9 hacer." },
  "Text size": { es: "Tama\u00f1o del texto" },
  "That one is for admins. Ask an admin to take a look.": { es: "Ese es para administradores. P\u00eddale a un administrador que lo revise." },
  "The connection dropped. Your answer is saved.": { es: "Se perdi\u00f3 la conexi\u00f3n. La respuesta qued\u00f3 guardada." },
  "The person reads your note in the app. Their notice shows only the dates.": { es: "La persona lee su nota en la aplicaci\u00f3n. Su aviso muestra solo las fechas." },
  "The schedule fills 8 weeks ahead and keeps extending until the pattern is ended.": { es: "El horario se llena con 8 semanas de anticipaci\u00f3n y sigue extendi\u00e9ndose hasta que el patr\u00f3n termine." },
  "The scheduled shift will be cancelled and posted as an open shift for eligible staff to claim.": { es: "El turno programado se cancela y se publica como turno abierto para que el personal elegible lo tome." },
  "The task will appear in the staff member's \"Assigned Tasks\" tab where they can mark it as in progress, resolved, or unable to resolve.": { es: "La tarea aparecer\u00e1 en la pesta\u00f1a \"Tareas asignadas\" de la persona, donde podr\u00e1 marcarla como en curso, resuelta o imposible de resolver." },
  "Then add it to your home screen from that browser.": { es: "Luego agr\u00e9guela a su pantalla de inicio desde ese navegador." },
  "This Month": { es: "Este mes" },
  "This Week": { es: "Esta semana" },
  "This issue is currently assigned to someone. Selecting a new person will remove the previous assignment.": { es: "Esta incidencia ya est\u00e1 asignada a alguien. Elegir a otra persona quita la asignaci\u00f3n anterior." },
  "This page is for admins.": { es: "Esta p\u00e1gina es para administradores." },
  "This photo could not be read here. Choose a JPEG or PNG, or take a screenshot of it.": { es: "No se pudo leer esta foto aqu\u00ed. Elija un JPEG o un PNG, o t\u00f3mele una captura de pantalla." },
  "This shift is open in the marketplace and available for staff to claim.": { es: "Este turno est\u00e1 abierto en el tablero y cualquier persona elegible puede tomarlo." },
  "This shift runs past midnight. Pick the day it starts.": { es: "Este turno pasa de la medianoche. Elija el d\u00eda en que comienza." },
  "This will permanently remove {0} and all associated tasks, assignments, and data. This action cannot be undone.": { es: "Esto eliminar\u00e1 de forma permanente {0} y todas sus tareas, asignaciones y datos. Esta acci\u00f3n no se puede deshacer." },
  "Thu": { es: "Jue" },
  "Time": { es: "Hora" },
  "Time off": { es: "Tiempo libre" },
  "Time off ({0})": { es: "Tiempo libre ({0})" },
  "Time off approved. They get a notice in the app.": { es: "Tiempo libre aprobado. La persona recibe un aviso en la aplicaci\u00f3n." },
  "Time off denied. They get a notice in the app.": { es: "Tiempo libre denegado. La persona recibe un aviso en la aplicaci\u00f3n." },
  "Time off request": { es: "Solicitud de tiempo libre" },
  "Timeline": { es: "Historial" },
  "Today": { es: "Hoy" },
  "Total": { es: "Total" },
  "Total Claimed": { es: "Total tomados" },
  "Total Pickups": { es: "Turnos tomados" },
  "Training": { es: "Capacitaci\u00f3n" },
  "Training Name": { es: "Nombre de la capacitaci\u00f3n" },
  "Training Type": { es: "Tipo de capacitaci\u00f3n" },
  "Training record added": { es: "Registro de capacitaci\u00f3n agregado" },
  "Training record deleted": { es: "Registro de capacitaci\u00f3n eliminado" },
  "Training record not found": { es: "No se encontr\u00f3 el registro de capacitaci\u00f3n" },
  "Training record updated": { es: "Registro de capacitaci\u00f3n actualizado" },
  "Try again": { es: "Intentar de nuevo" },
  "Try clearing filters.": { es: "Pruebe a quitar los filtros." },
  "Tue": { es: "Mar" },
  "Type": { es: "Tipo" },
  "Type a message": { es: "Escriba un mensaje" },
  "Type {0} here": { es: "Escriba {0} aqu\u00ed" },
  "Type {0} to confirm": { es: "Escriba {0} para confirmar" },
  "Type {0} to confirm.": { es: "Escriba {0} para confirmar." },
  "URGENT": { es: "URGENTE" },
  "Unable to Resolve": { es: "No se pudo resolver" },
  "Unassigned": { es: "Sin asignar" },
  "Uncategorized": { es: "Sin categor\u00eda" },
  "Unfinished reports": { es: "Informes sin terminar" },
  "Unknown": { es: "Desconocido" },
  "Until": { es: "Hasta" },
  "Upcoming": { es: "Pr\u00f3ximos" },
  "Upcoming Shifts (Next 7 Days)": { es: "Pr\u00f3ximos turnos (siguientes 7 d\u00edas)" },
  "Updated": { es: "Actualizado" },
  "Upload File": { es: "Subir un archivo" },
  "Upload a photo or video (up to 50MB), or paste a YouTube link above": { es: "Suba una foto o un video (hasta 50 MB), o pegue arriba un enlace de YouTube" },
  "Upload failed": { es: "No se pudo subir el archivo" },
  "Upload failed ({0}): {1}": { es: "No se pudo subir el archivo ({0}): {1}" },
  "Upload failed: {0}": { es: "No se pudo subir el archivo: {0}" },
  "Uploaded": { es: "Archivo subido" },
  "Uploaded By": { es: "Subido por" },
  "Uploading...": { es: "Subiendo..." },
  "Urgency": { es: "Urgencia" },
  "Urgent": { es: "Urgente" },
  "Valid": { es: "Vigente" },
  "Vendor / W-9": { es: "Proveedor / W-9" },
  "Vendor Registry": { es: "Registro de proveedores" },
  "Vendors": { es: "Proveedores" },
  "View": { es: "Ver" },
  "View All": { es: "Ver todo" },
  "View PDF": { es: "Ver el PDF" },
  "View all": { es: "Ver todo" },
  "View shift": { es: "Ver el turno" },
  "View site": { es: "Ver el sitio" },
  "Voluntary Drop": { es: "Baja voluntaria" },
  "Voluntary Drops": { es: "Bajas voluntarias" },
  "Wed": { es: "Mi\u00e9" },
  "Week": { es: "Semana" },
  "Weekly": { es: "Semanal" },
  "Weekly Trend": { es: "Tendencia semanal" },
  "Weekly pattern": { es: "Patr\u00f3n semanal" },
  "Welcome back, {0}": { es: "Bienvenido de nuevo, {0}" },
  "Welcome, {0}": { es: "Bienvenido, {0}" },
  "Work Started": { es: "Trabajo iniciado" },
  "Worked": { es: "Trabajados" },
  "Working from the written procedure only right now.": { es: "Por ahora trabajo solo con el procedimiento escrito." },
  "You can send up to 3 photos with one message.": { es: "Puede enviar hasta 3 fotos con un mensaje." },
  "YouTube link attached": { es: "Enlace de YouTube adjunto" },
  "Your messages": { es: "Sus mensajes" },
  "Zip": { es: "C\u00f3digo postal" },
  "Zone": { es: "Zona" },
  "Zone *": { es: "Zona *" },
  "Zones": { es: "Zonas" },
  "annual": { es: "anual" },
  "biweekly": { es: "quincenal" },
  "by {0}": { es: "por {0}" },
  "clock in": { es: "entrada registrada" },
  "critical": { es: "cr\u00edtica" },
  "e.g. 1": { es: "p. ej. 1" },
  "e.g. 1, 2, B": { es: "p. ej. 1, 2, B" },
  "e.g. 95% or Pass": { es: "p. ej. 95% o Aprobado" },
  "e.g. Clean window blinds in conference room": { es: "p. ej. Limpiar las persianas de la sala de reuniones" },
  "e.g. Complete bloodborne pathogens training": { es: "p. ej. Completar la capacitaci\u00f3n sobre pat\u00f3genos transmitidos por la sangre" },
  "e.g. General Cleaning Training": { es: "p. ej. Capacitaci\u00f3n general de limpieza" },
  "e.g. Main": { es: "p. ej. Principal" },
  "e.g. Marcus called out": { es: "p. ej. una persona se report\u00f3 ausente" },
  "e.g. Marcus called out sick": { es: "p. ej. una persona se report\u00f3 enferma" },
  "e.g. Offices": { es: "p. ej. Oficinas" },
  "e.g. Restrooms": { es: "p. ej. Ba\u00f1os" },
  "e.g. Vacuum carpets": { es: "p. ej. Aspirar las alfombras" },
  "e.g. {0}": { es: "p. ej. {0}" },
  "ends next day": { es: "termina al d\u00eda siguiente" },
  "ends {0}": { es: "termina el {0}" },
  "high": { es: "alta" },
  "in progress": { es: "en curso" },
  "issue reported": { es: "incidencia reportada" },
  "low": { es: "baja" },
  "medium": { es: "media" },
  "message sent": { es: "mensaje enviado" },
  "monthly": { es: "mensual" },
  "note: {0}": { es: "nota: {0}" },
  "of {0} active": { es: "de {0} activos" },
  "pending": { es: "pendiente" },
  "quarterly": { es: "trimestral" },
  "shift created": { es: "turno creado" },
  "shift deleted": { es: "turno eliminado" },
  "shift updated": { es: "turno actualizado" },
  "site assigned": { es: "sitio asignado" },
  "site unassigned": { es: "sitio desasignado" },
  "standard": { es: "est\u00e1ndar" },
  "supply logged": { es: "suministro registrado" },
  "task completed": { es: "tarea completada" },
  "to {0}": { es: "a {0}" },
  "today": { es: "hoy" },
  "unable to resolve": { es: "no se pudo resolver" },
  "urgent": { es: "urgente" },
  "weekly": { es: "semanal" },
  "weeks": { es: "semanas" },
  "yesterday": { es: "ayer" },
  "{0} Admin": { es: "{0} Administraci\u00f3n" },
  "{0} Supervisor": { es: "{0} Supervisi\u00f3n" },
  "{0} added, {1} removed, {2} kept": { es: "{0} agregados, {1} quitados, {2} conservados" },
  "{0} added, {1} removed, {2} total": { es: "{0} agregados, {1} eliminados, {2} en total" },
  "{0} at {1}": { es: "{0} en {1}" },
  "{0} cases need attention": { es: "{0} casos necesitan atenci\u00f3n" },
  "{0} claimed": { es: "{0} tomados" },
  "{0} claimed with overtime risk": { es: "{0} tomados con riesgo de horas extra" },
  "{0} claims": { es: "{0} tomados" },
  "{0} dates were skipped because this person is already scheduled at that time:": { es: "Se omitieron {0} fechas porque esta persona ya tiene un turno a esa hora:" },
  "{0} days ago": { es: "hace {0} d\u00edas" },
  "{0} of {1}": { es: "{0} de {1}" },
  "{0} of {1} answered": { es: "{0} de {1} respondidas" },
  "{0} of {1} tasks": { es: "{0} de {1} tareas" },
  "{0} open": { es: "{0} abiertos" },
  "{0} open issues": { es: "{0} incidencias abiertas" },
  "{0} pending": { es: "{0} pendientes" },
  "{0} scheduled": { es: "{0} programados" },
  "{0} staff": { es: "{0} personas" },
  "{0} started": { es: "{0} iniciados" },
  "{0} to {1}": { es: "{0} a {1}" },
  "{0} total, {1} callouts": { es: "{0} en total, {1} ausencias" },
  "{0} unread notifications": { es: "{0} avisos sin leer" },
  "{0}% callouts": { es: "{0}% de ausencias" },
  "{0}% filled": { es: "{0}% cubierto" },
  "{0}/{1} filled": { es: "{0}/{1} cubiertos" },
  "{0}d": { es: "{0}d" },
  "{0}h": { es: "{0}h" },
  "{0}m": { es: "{0}m" },
  "{0}w ago": { es: "hace {0} sem." },
  // One English word, two Spanish ones. The context after the bar names the noun the Spanish
  // adjective has to agree with.
  "Active|pattern": { es: "Activo" },
  "Active|person": { es: "Activa" },
  "Active|sites": { es: "Activos" },
  "All|patterns": { es: "Todos" },
  "All|people": { es: "Todas" },
  "All|requests": { es: "Todas" },
  "All|shifts": { es: "Todos" },
  "All|sites": { es: "Todos" },
  "All|timeline": { es: "Todo" },
  "Approved|request": { es: "Aprobada" },
  "Approved|shift": { es: "Aprobado" },
  "Assigned|issue": { es: "Asignada" },
  "Assigned|shift": { es: "Asignado" },
  "Assigned|task": { es: "Asignada" },
  "Cancelled|inspection": { es: "Cancelada" },
  "Cancelled|request": { es: "Cancelada" },
  "Cancelled|shift": { es: "Cancelado" },
  "Claimed|shift": { es: "Tomado" },
  "Closed|case": { es: "Cerrado" },
  "Closed|shift": { es: "Cerrado" },
  "Completed|inspection": { es: "Completada" },
  "Completed|shift": { es: "Completado" },
  "DOC|source": { es: "DOC" },
  "Denied|request": { es: "Denegada" },
  "Ended|pattern": { es: "Terminado" },
  "Expired|filter": { es: "Vencidos" },
  "Expired|item": { es: "Vencido" },
  "Inactive|sites": { es: "Inactivos" },
  "JF|source": { es: "JF" },
  "New|request": { es: "Nueva" },
  "New|shift": { es: "Nuevo" },
  "None|activity": { es: "Ninguna" },
  "None|inspection": { es: "Ninguna" },
  "None|note": { es: "Ninguna" },
  "None|site": { es: "Ninguno" },
  "None|shifts": { es: "Ninguno" },
  "ONB|source": { es: "INC" },
  "Open|issue": { es: "Abierta" },
  "Open|shift": { es: "Abierto" },
  "Other|items": { es: "Otros" },
  "Pending|pickups": { es: "Pendientes" },
  "Released|shift": { es: "Liberado" },
  "Removed|task": { es: "Tarea quitada" },
  "Requested|request": { es: "Solicitada" },
  "Scheduled|inspection": { es: "Programada" },
  "Scheduled|shift": { es: "Programado" },
  "Start|work": { es: "Iniciar" },
  "TR|source": { es: "CAP" },
  "Time|section": { es: "Horarios" },
  "active|person": { es: "activa" },
  "active|site": { es: "activo" },
  "all|issues": { es: "todas" },
  "assigned|task": { es: "asignada" },
  "closed|issue": { es: "cerrada" },
  "completed at|field": { es: "fecha de finalizaci\u00f3n" },
  "completed|item": { es: "completado" },
  "created at|field": { es: "fecha de creaci\u00f3n" },
  "description|field": { es: "descripci\u00f3n" },
  "escalated|issue": { es: "escalada" },
  "escalated|issues": { es: "escaladas" },
  "inactive|person": { es: "inactiva" },
  "inactive|site": { es: "inactivo" },
  "kind|field": { es: "tipo" },
  "label|field": { es: "nombre" },
  "notes|field": { es: "notas" },
  "open|issue": { es: "abierta" },
  "open|issues": { es: "abiertas" },
  "priority|field": { es: "prioridad" },
  "reported at|field": { es: "fecha del reporte" },
  "resolved|issue": { es: "resuelta" },
  "resolved|issues": { es: "resueltas" },
  "resolved|task": { es: "resuelta" },
  "severity|field": { es: "gravedad" },
  "site name|field": { es: "nombre del sitio" },
  "status|field": { es: "estado" },
  "submitted|item": { es: "enviado" },
  "title|field": { es: "t\u00edtulo" },
  "to|between two dates": { es: "a" },
  "updated at|field": { es: "fecha de actualizaci\u00f3n" },
  "zone|field": { es: "zona" },
  // A count choice, one entry per form the language has. English has two; Spanish has two; a
  // language with more picks its own through Intl.PluralRules.
  "{0} hour|count": {
    en: { one: "{0} hour", other: "{0} hours" },
    es: { one: "{0} hora", other: "{0} horas" },
  },
  "{0} inspection|count": {
    en: { one: "{0} inspection", other: "{0} inspections" },
    es: { one: "{0} inspecci\u00f3n", other: "{0} inspecciones" },
  },
  "{0} shift claimed with overtime risk|count": {
    en: { one: "{0} shift claimed with overtime risk", other: "{0} shifts claimed with overtime risk" },
    es: { one: "{0} turno tomado con riesgo de horas extra", other: "{0} turnos tomados con riesgo de horas extra" },
  },
  "{0} started today|count": {
    en: { one: "{0} started today", other: "{0} started today" },
    es: { one: "{0} iniciado hoy", other: "{0} iniciados hoy" },
  },
  "{0} started on {1}|count": {
    en: { one: "{0} started on {1}", other: "{0} started on {1}" },
    es: { one: "{0} iniciado el {1}", other: "{0} iniciados el {1}" },
  },
  "{0} started|count": {
    en: { one: "{0} started", other: "{0} started" },
    es: { one: "{0} iniciado", other: "{0} iniciados" },
  },
  "{0} no-show|count": {
    en: { one: "{0} no-show", other: "{0} no-shows" },
    es: { one: "{0} no se present\u00f3", other: "{0} no se presentaron" },
  },
  "{0} message|count": {
    en: { one: "{0} message", other: "{0} messages" },
    es: { one: "{0} mensaje", other: "{0} mensajes" },
  },
  "{0} entry|count": {
    en: { one: "{0} entry", other: "{0} entries" },
    es: { one: "{0} registro", other: "{0} registros" },
  },
  "{0} staff|count": {
    en: { one: "{0} staff", other: "{0} staff" },
    es: { one: "{0} persona", other: "{0} personas" },
  },
  "{0} task|count": {
    en: { one: "{0} task", other: "{0} tasks" },
    es: { one: "{0} tarea", other: "{0} tareas" },
  },
  "{0}mo ago|count": {
    en: { one: "{0}mo ago", other: "{0}mo ago" },
    es: { one: "hace {0} mes", other: "hace {0} meses" },
  },
  "{0}y ago|count": {
    en: { one: "{0}y ago", other: "{0}y ago" },
    es: { one: "hace {0} a\u00f1o", other: "hace {0} a\u00f1os" },
  },
  "{0} employee|count": {
    en: { one: "{0} employee", other: "{0} employees" },
    es: { one: "{0} persona", other: "{0} personas" },
  },
  "{0} expired|count": {
    en: { one: "{0} expired", other: "{0} expired" },
    es: { one: "{0} vencido", other: "{0} vencidos" },
  },
  "{0} expiring|count": {
    en: { one: "{0} expiring", other: "{0} expiring" },
    es: { one: "{0} por vencer", other: "{0} por vencer" },
  },
  "{0} document|count": {
    en: { one: "{0} document", other: "{0} documents" },
    es: { one: "{0} documento", other: "{0} documentos" },
  },
  "{0} record|count": {
    en: { one: "{0} record", other: "{0} records" },
    es: { one: "{0} registro", other: "{0} registros" },
  },
  "{1} of {0} steps complete|count": {
    en: { one: "{1} of {0} step complete", other: "{1} of {0} steps complete" },
    es: { one: "{1} de {0} paso completado", other: "{1} de {0} pasos completados" },
  },
  "{0} item|count": {
    en: { one: "{0} item", other: "{0} items" },
    es: { one: "{0} elemento", other: "{0} elementos" },
  },
};

// The language the screen is being drawn in. The app sets it before anything renders and again on
// every change, the way it sets the theme, so tr() reads one value rather than taking one.
let current = "en";
export function setLang(id) { current = LOCALES.indexOf(id) >= 0 ? id : "en"; }
export function getLang() { return current; }
export function localeTag(lang) { return LOCALE_TAGS[lang || current] || LOCALE_TAGS.en; }

// What a browser says it wants, when nothing is stored.
export function browserLang() {
  try {
    const want = (navigator.languages && navigator.languages.length ? navigator.languages : [navigator.language]) || [];
    for (let i = 0; i < want.length; i += 1) {
      const two = String(want[i] || "").slice(0, 2).toLowerCase();
      if (LOCALES.indexOf(two) >= 0) return two;
    }
  } catch (e) { /* a browser that will not say is an English one */ }
  return "en";
}

const fill = (text, values) => String(text).replace(/\{(\d+)\}/g, (m, i) => {
  const v = values[Number(i)];
  return v === undefined || v === null ? "" : String(v);
});
// The text before the bar, which is the English a key falls back to.
const baseOf = (key) => { const i = String(key).lastIndexOf("|"); return i > 0 ? String(key).slice(0, i) : String(key); };

export function tr(key, ...values) {
  const entry = WORDS[key];
  const said = entry && typeof entry[current] === "string" && entry[current] !== "" ? entry[current] : null;
  return fill(said === null ? baseOf(key) : said, values);
}

const RULES = {};
function rulesFor(lang) {
  if (!RULES[lang]) {
    try { RULES[lang] = new Intl.PluralRules(localeTag(lang)); }
    catch (e) { RULES[lang] = { select: (n) => (Number(n) === 1 ? "one" : "other") }; }
  }
  return RULES[lang];
}

// A count and its word, in whichever form the language uses for that number. {0} is the count.
export function trn(key, count, ...values) {
  const entry = WORDS[key] || {};
  const pick = (forms, lang) => {
    if (!forms || typeof forms !== "object") return null;
    const form = rulesFor(lang).select(Number(count));
    return forms[form] !== undefined ? forms[form] : (forms.other !== undefined ? forms.other : null);
  };
  const said = pick(entry[current], current);
  const english = said === null ? pick(entry.en, "en") : said;
  return fill(english === null ? baseOf(key) : english, [count].concat(values));
}
